import Link from "next/link";
import { MapPin } from "lucide-react";
import ReraBadge, { reraTextClass } from "@/components/Common/ReraBadge";
import ImageCarousel from "@/components/Carousel";
import AmenitiesShowcase from "@/components/Project/listing/AmenitiesShowcase";
import SpecificationsAccordion from "@/components/Project/intelligence/SpecificationsAccordion";
import HighlightStats from "@/components/Project/listing/HighlightStats";
import ScoreRing from "@/components/Project/listing/ScoreRing";
import Faq from "@/components/Project/intelligence/Faq";
import { instrumentSerif, manrope } from "@/lib/fonts";
import type { PropertyView } from "@/lib/intelligence/property-view";
import SaveToggleButton from "@/components/Common/SaveToggleButton";

const ROUTE_BASE: Record<PropertyView["category"], string> = {
  Sale: "buy-property",
  Rent: "rent-property",
  Pg: "pg-property",
  Commercial: "commercial",
};

export default function PropertyDetailView({ view }: { view: PropertyView }) {
  const routeBase = ROUTE_BASE[view.category];

  return (
    // flow-root establishes a block formatting context so the last section's
    // own bottom margin (my-14 on the Enquiry CTA) is contained inside this
    // div's painted background instead of collapsing through it — without it,
    // that margin rendered as a gap of bare (white) page background between
    // this section and the footer.
    <div className={`${instrumentSerif.variable} ${manrope.variable} font-ui min-h-screen flow-root bg-[#0B0B0C] text-white`}>
      {/* Hero */}
      <section className="relative w-full h-[52vh] min-h-[360px] overflow-hidden">
        {view.heroImage ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={view.heroImage} alt={view.title} className="absolute inset-0 h-full w-full object-cover" />
        ) : (
          <div className="absolute inset-0 bg-gradient-to-br from-[#1a1a1d] to-[#0B0B0C]" />
        )}
        <div className="absolute inset-0 bg-gradient-to-t from-[#0B0B0C] via-[#0B0B0C]/40 to-transparent" />
        <div className="absolute bottom-0 left-0 w-full max-w-7xl mx-auto px-4 md:px-2 pb-8">
          <Link href={`/${routeBase}`} className="text-sm text-[#D9B268] hover:opacity-80">
            ← Back to {view.category} listings
          </Link>
          <div className="flex flex-wrap items-center gap-2 mt-3 mb-2">
            {view.propertyType && (
              <span className="rounded-full border border-white/15 bg-black/40 px-3 py-1 text-xs font-semibold">
                {view.propertyType}
              </span>
            )}
            <span className="rounded-full border border-white/15 bg-black/40 px-3 py-1 text-xs font-semibold">
              {view.status}
            </span>
            {view.rera && <ReraBadge reraId={view.rera} status={view.reraStatus} variant="full" />}
          </div>
          <div className="flex flex-wrap items-start justify-between gap-3">
            <h1 className="font-display text-3xl md:text-5xl font-normal tracking-tight text-white max-w-4xl">
              {view.title}
            </h1>
            <SaveToggleButton
              item={{
                itemType: "property",
                citySegment: view.citySlug,
                slug: view.slug,
                propertyId: view.id,
                category: view.category,
                title: view.title,
                imageUrl: view.heroImage,
                priceText: view.priceText,
                locationText: view.location,
              }}
            />
          </div>
          <p className="flex items-center gap-1.5 text-gray-300 mt-2">
            <MapPin size={16} /> {view.location}
          </p>
          <p className="text-2xl md:text-3xl font-bold text-[#D9B268] mt-4">{view.priceText}</p>
        </div>
      </section>

      <div className="max-w-7xl mx-auto px-4 md:px-2">
        {/* Gallery */}
        {view.images.length > 0 && (
          <section className="my-10">
            <ImageCarousel images={view.images} alt={view.title} />
          </section>
        )}

        {/* Snapshot chips */}
        {view.snapshot.length > 0 && (
          <section className="my-10 grid grid-cols-2 md:grid-cols-4 gap-4">
            {view.snapshot.map((chip) => (
              <div key={chip.label} className="rounded-xl border border-white/[0.08] bg-[#141416] p-4">
                <p className="text-xs text-gray-500 mb-1">{chip.label}</p>
                <p className={`text-sm font-semibold ${chip.label === "RERA" ? reraTextClass(chip.value, chip.status) : "text-white"}`}>
                  {chip.value}
                </p>
              </div>
            ))}
          </section>
        )}

        {/* AI summary — one-time generated by the backend's enrichment tier,
            not a live per-page-load call. Absent until that's run. */}
        {view.aiSummary && (
          <section className="my-10 rounded-xl border border-[#D9B268]/20 bg-[#D9B268]/5 p-6">
            <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#D9B268] mb-2">Overview</p>
            <p className="text-gray-200 leading-relaxed">{view.aiSummary}</p>
          </section>
        )}

        {/* Why this listing */}
        {view.whyThisListing.length > 0 && (
          <section className="my-10">
            <h2 className="text-2xl bg-gradient-to-b from-[#FDF094] to-[#B77D2B] font-bold bg-clip-text text-transparent mb-6">
              Why this listing
            </h2>
            <div className="flex flex-wrap gap-3">
              {view.whyThisListing.map((badge) => (
                <div
                  key={badge.label}
                  className="rounded-xl border border-white/[0.08] bg-[#141416] px-4 py-3 min-w-[180px]"
                >
                  <p className="text-sm font-semibold text-white">{badge.label}</p>
                  {badge.note && <p className="text-xs text-gray-500 mt-0.5">{badge.note}</p>}
                </div>
              ))}
            </div>
          </section>
        )}

        <HighlightStats title={view.title} stats={view.highlightStats} />

        {/* Investment score — real backend enrichment output, not a
            client-side heuristic. Absent until scoring has run. */}
        {view.investmentScore && (
          <section className="my-10 flex flex-col md:flex-row items-center gap-8 rounded-xl border border-white/[0.08] bg-[#141416] p-8">
            <ScoreRing score={view.investmentScore.score} grade={view.investmentScore.grade} size={140} />
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#D9B268] mb-2">
                Homz Score — {view.investmentScore.grade}
              </p>
              <p className="text-gray-300 max-w-2xl">{view.investmentScore.verdict}</p>
              <div className="flex gap-6 mt-4 text-sm">
                {view.investmentScore.riskScore != null && (
                  <p className="text-gray-400">
                    Risk score: <span className="text-white font-semibold">{view.investmentScore.riskScore}</span>
                  </p>
                )}
                {view.investmentScore.locationScore != null && (
                  <p className="text-gray-400">
                    Location score:{" "}
                    <span className="text-white font-semibold">{view.investmentScore.locationScore}</span>
                  </p>
                )}
              </div>
            </div>
          </section>
        )}

        {/* Key highlights */}
        {view.keyHighlights.length > 0 && (
          <section className="my-10">
            <h2 className="text-2xl bg-gradient-to-b from-[#FDF094] to-[#B77D2B] font-bold bg-clip-text text-transparent mb-6">
              Key Highlights
            </h2>
            <ul className="space-y-2">
              {view.keyHighlights.map((h) => (
                <li key={h} className="flex gap-2 text-gray-300">
                  <span className="text-[#D9B268]">•</span> {h}
                </li>
              ))}
            </ul>
          </section>
        )}

        {view.amenities.length > 0 && <AmenitiesShowcase title={view.title} data={view.amenities} />}
        {view.specifications.length > 0 && (
          <SpecificationsAccordion title={view.title} specifications={view.specifications} />
        )}

        {/* Landmarks — real, scraped data, not a live Google Places call */}
        {Object.keys(view.landmarks).length > 0 && (
          <section className="my-12">
            <h2 className="text-2xl bg-gradient-to-b from-[#FDF094] to-[#B77D2B] font-bold bg-clip-text text-transparent mb-6">
              What&apos;s Nearby
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {Object.entries(view.landmarks).map(([category, items]) => (
                <div key={category} className="rounded-xl border border-white/[0.08] bg-[#141416] p-4">
                  <p className="text-xs font-bold uppercase tracking-wider text-[#D9B268] mb-2">{category}</p>
                  <ul className="space-y-1.5">
                    {items.slice(0, 5).map((item) => (
                      <li key={item.name} className="flex justify-between text-sm text-gray-300">
                        <span>{item.name}</span>
                        <span className="text-gray-500">{item.distance}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Persona reasons */}
        {(view.personaReasons.investor.length > 0 || view.personaReasons.endUser.length > 0) && (
          <section className="my-12 grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#D9B268] mb-3">For Investors</p>
              <div className="space-y-3">
                {view.personaReasons.investor.map((b) => (
                  <div key={b.label} className="rounded-xl border border-white/[0.08] bg-[#141416] p-4">
                    <p className="text-sm font-semibold text-white">{b.label}</p>
                    {b.note && <p className="text-xs text-gray-500 mt-0.5">{b.note}</p>}
                  </div>
                ))}
              </div>
            </div>
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#D9B268] mb-3">For End Users</p>
              <div className="space-y-3">
                {view.personaReasons.endUser.map((b) => (
                  <div key={b.label} className="rounded-xl border border-white/[0.08] bg-[#141416] p-4">
                    <p className="text-sm font-semibold text-white">{b.label}</p>
                    {b.note && <p className="text-xs text-gray-500 mt-0.5">{b.note}</p>}
                  </div>
                ))}
              </div>
            </div>
          </section>
        )}

        {view.about.length > 0 && (
          <section className="my-12">
            <h2 className="text-2xl bg-gradient-to-b from-[#FDF094] to-[#B77D2B] font-bold bg-clip-text text-transparent mb-6">
              About This Listing
            </h2>
            <div className="space-y-3 text-gray-300 leading-relaxed">
              {view.about.map((p, i) => (
                <p key={i}>{p}</p>
              ))}
            </div>
          </section>
        )}

        <Faq title={view.title} items={view.faq} />

        {/* Enquiry CTA */}
        <section className="my-14 rounded-2xl border border-[#D9B268]/20 bg-gradient-to-br from-[#1a1a1d] to-[#0B0B0C] p-8 text-center">
          <h2 className="font-display text-2xl md:text-3xl text-white mb-3">Interested in this listing?</h2>
          <p className="text-gray-400 mb-6">Get in touch and we&apos;ll help you take the next step.</p>
          <Link
            href="/contact"
            className="inline-block rounded-full bg-gradient-to-br from-[#F2D79B] to-[#C99A4B] px-8 py-3 font-bold text-[#1c1608]"
          >
            Contact Now
          </Link>
          {view.listingUrl && (
            <p className="mt-4 text-xs text-gray-500">
              <a href={view.listingUrl} target="_blank" rel="noopener noreferrer" className="underline hover:text-gray-300">
                View original listing
              </a>
            </p>
          )}
        </section>
      </div>
    </div>
  );
}
